name: entity
version: 3.3.2
description: A simple ORM for Relational and NoSQL database, such as Couchbase and PostgreSQL.
homepage: https://github.com/rikulo/entity
documentation: https://github.com/rikulo/entity
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  postgresql2: '>=1.0.0'
  charcode: '>=1.0.0 <2.0.0'
  rikulo_commons: '>=3.0.0'

dev_dependencies:
  test: any
